(() => {
  window.stagesConfig = [
    {
      id: 1,
      version: 1,
      name: "Stage 1",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      noRepeatAcrossRounds: true,
      tabTutorialEnabled: true,
      revealSeconds: 5,
      recallSeconds: 30,
      categories: ["numbers"],
      cardCounts: {},
      modifiers: {},
      starTimes: { platinum: 2, gold: 3, silver: 8, bronze: 20 },
      instructions: window.stageInstructions[1] || []
    },
    {
      id: 2,
      version: 1,
      name: "Stage 2",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      noRepeatAcrossRounds: true,
      tabTutorialEnabled: true,
      revealSeconds: 5,
      recallSeconds: 30,
      categories: ["letters"],
      cardCounts: {},
      modifiers: {},
      starTimes: { platinum: 2, gold: 3, silver: 8, bronze: 20 },
      instructions: window.stageInstructions[2] || []
    },
    {
      id: 3,
      version: 1,
      name: "Stage 3",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      noRepeatAcrossRounds: true,
      tabTutorialEnabled: true,
      firstLetterHintMessage: "FIRST LETTER\n(Triangle -> T, Circle -> C, Square -> S)",
      revealSeconds: 5,
      recallSeconds: 30,
      categories: ["shapes"],
      cardCounts: {},
      modifiers: {},
      starTimes: { platinum: 2, gold: 3, silver: 8, bronze: 20 },
      instructions: window.stageInstructions[3] || []
    },
    {
      id: 4,
      version: 1,
      name: "Stage 4",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      noRepeatAcrossRounds: true,
      tabTutorialEnabled: true,
      firstLetterHintMessage: "FIRST LETTER (Right -> R, Left -> L, Up -> U, Down -> D) \nArrow keys (↑,↓,←,→). Cardinal directions (N,E,S,W)",
      revealSeconds: 5,
      recallSeconds: 30,
      categories: ["directions"],
      cardCounts: {},
      modifiers: {},
      starTimes: { platinum: 2, gold: 3, silver: 8, bronze: 20 },
      instructions: window.stageInstructions[4] || []
    },
    {
      id: 5,
      version: 1,
      name: "Stage 5",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      noRepeatAcrossRounds: true,
      uniqueCardTypesPerRound: true,
      revealSeconds: 10,
      recallSeconds: 30,
      categories: ["numbers", "letters", "directions", "shapes"],
      cardCounts: {},
      modifiers: {},
      starTimes: { platinum: 2, gold: 3, silver: 8, bronze: 20 },
      instructions: window.stageInstructions[5] || []
    }
  ];
})();

  // mathOps: true,
  // mathChance: 0.9,
  // misleadColors: true,
  // misleadChance: 0.4,
  // backgroundColor: true,
  // backgroundColorChance: 1.0,
  // backgroundPromptChance: 0.5
  // swapCards: true,
  // swapChance: 0.3,
  // platformer: false,
  // glitch: false,
  // fog: false,
  // ads: false
