(() => {
  window.stagesConfig = [
    {
      id: 1,
      version: 1,
      name: "Stage 1",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 30,
      recallSeconds: 30,
      categories: ["numbers"],
      cardCounts: {},
      modifiers: {
        mathOps: false,
        mathChance: 0.7,
        mathMinCount: null,
        mathMaxCount: null,
        misleadColors: false,
        misleadChance: 0.6,
        misleadMinCount: null,
        misleadMaxCount: null,
        backgroundColor: false,
        backgroundColorChance: 0.35,
        backgroundPromptChance: 0.5,
        backgroundPromptMinCount: null,
        backgroundPromptMaxCount: null,
        swapCards: false,
        swapChance: 1,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 2, gold: 3, silver: 8, bronze: 20 },
      instructions: window.stageInstructions[1] || []
    },
    {
      id: 2,
      version: 1,
      name: "Stage 2",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      revealSeconds: 30,
      recallSeconds: 30,
      categories: ["numbers"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 3, gold: 4, silver: 16, bronze: 30 },
      instructions: window.stageInstructions[2] || [],
    },
    {
      id: 3,
      version: 1,
      name: "Stage 3",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["letters"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 },
      instructions: window.stageInstructions[3] || []
    },
    {
      id: 4,
      version: 1,
      name: "Stage 4",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 },
    },
    {
      id: 5,
      version: 1,
      name: "Stage 5",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["shapes"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 2, gold: 3, silver: 10, bronze: 20 },
      instructions: window.stageInstructions[5] || []
    },
    {
      id: 6,
      version: 1,
      name: "Stage 6",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 },
      instructions: window.stageInstructions[6] || []
    },
    {
      id: 7,
      version: 1,
      name: "Stage 7",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 2, gold: 3, silver: 10, bronze: 20 },
      instructions: window.stageInstructions[7] || []
    },
    {
      id: 8,
      version: 1,
      name: "Stage 8",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "directions", "shapes"],
      roundCategoryGuarantee: ["numbers", "directions", "shapes"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 5, gold: 6, silver: 10, bronze: 20 },
    },
    {
      id: 9,
      version: 1,
      name: "Stage 9",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters"],
      roundCategoryGuarantee: ["numbers", "colors", "letters"],
      modifiers: {
        mathOps: false,
        misleadColors: false,
        backgroundColor: false,
        swapCards: false,
        platformer: false,
        glitch: false,
        fog: false,
        ads: false
      },
      starTimes: { platinum: 3, gold: 4, silver: 10, bronze: 20 },
    },
    {
      id: 10,
      version: 1,
      name: "Stage 10",
      stageType: "memory",
      rounds: 2,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "shapes", "directions"],
      modifiers: {
      },
      starTimes: { platinum: 3.5, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 11,
      version: 1,
      name: "Stage 11",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
      },
      starTimes: { platinum: 1.8, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 12,
      version: 1,
      name: "Stage 12",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        mathOps: true,
        mathChance: 1.0,
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 },
      instructions: window.stageInstructions[12] || []
    },
    {
      id: 13,
      version: 1,
      name: "Stage 13",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        mathOps: true,
        mathChance: 0.7,
      },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 14,
      version: 1,
      name: "Stage 14",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      cardCounts: { numbers: 1},
      modifiers: {
        mathOps: true,
        mathChance: 1.0,
        mathMinCount: 1,
        mathMaxCount: 1
      },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 15,
      version: 1,
      name: "Stage 15",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["letters", "shapes"],
      roundCategoryGuarantee: ["letters", "shapes"],
      modifiers: {
      },
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 16,
      version: 1,
      name: "Stage 16",
      stageType: "tutorial",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 1.0,
        backgroundPromptChance: 1.0,
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 },
      instructions: window.stageInstructions[16] || []
    },
    {
      id: 17,
      version: 1,
      name: "Stage 17",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters", "shapes"],
      roundCategoryGuarantee: ["numbers", "letters", "shapes"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 1.0,
        backgroundPromptChance: 0.5
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 18,
      version: 1,
      name: "Stage 18",
      stageType: "memory",
      rounds: 2,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters", "directions", "shapes"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 1.0,
        backgroundPromptChance: 0.5
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 19,
      version: 1,
      name: "Stage 19",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 30,
      categories: ["shapes", "directions"],
      modifiers: {
      },
      starTimes: { platinum: 2.5, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 20,
      version: 1,
      name: "Stage 20",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 30,
      recallSeconds: 30,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 0.7,
        backgroundPromptChance: 0.5,
        mathOps: true,
        mathChance: 1.0
      },
      starTimes: { platinum: 3.5, gold: 4, silver: 20, bronze: 30 }
    },
    {
      id: 21,
      version: 1,
      name: "Stage 21",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 30,
      categories: ["colors", "directions"],
      modifiers: {
      },
      starTimes: { platinum: 2, gold: 3, silver: 15, bronze: 20 },
      instructions: window.stageInstructions[21] || []
    },
    {
      id: 22,
      version: 1,
      name: "Stage 22",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 30,
      recallSeconds: 30,
      categories: ["colors"],
      modifiers: {
        misleadColors: true,
        misleadChance: 1.0
      },
      starTimes: { platinum: 2, gold: 3, silver: 15, bronze: 20 },
    },
    {
      id: 23,
      version: 1,
      name: "Stage 23",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: {
        misleadColors: true,
        misleadChance: 1.0,
        backgroundColor: true,
        backgroundColorChance: 0.7,
        backgroundPromptChance: 0.5,
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 24,
      version: 1,
      name: "Stage 24",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: {
        misleadColors: true,
        misleadChance: 1.0,
        backgroundColor: true,
        backgroundColorChance: 0.7,
        backgroundPromptChance: 0.5,
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 25,
      version: 1,
      name: "Stage 25",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: {
        misleadColors: true,
        misleadChance: 1.0,
        backgroundColor: true,
        backgroundColorChance: 0.7,
        backgroundPromptChance: 0.5,
      },
      starTimes: { platinum: 2.5, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 26,
      version: 1,
      name: "Stage 26",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      modifiers: {
        mathOps: true,
        mathChance: 1.0
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 27,
      version: 1,
      name: "Stage 27",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["diagonal"],
      modifiers: {},
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 },
      instructions: window.stageInstructions[27] || []
    },
    {
      id: 28,
      version: 1,
      name: "Stage 28",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions", "diagonal"],
      modifiers: {},
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 29,
      version: 1,
      name: "Stage 29",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes", "diagonal"],
      modifiers: {
        mathOps: true,
        mathChance: 0.5
      },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 30,
      version: 1,
      name: "Stage 30",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["diagonal", "directions"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 0.7,
        backgroundPromptChance: 0.5,
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 31,
      version: 1,
      name: "Stage 31",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters", "colors"],
      modifiers: { 
        textColor: true,
        textColorChance: 1.0,
        textPromptChance: 1.0 
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 32,
      version: 1,
      name: "Stage 32",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "directions", "letters"],
      modifiers: { textColor: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 33,
      version: 1,
      name: "Stage 33",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { 
        misleadColors: true, 
        misleadChance: 0.6,
        textColor: true,
        textColorChance: 1.0,
        textPromptChance: 0.5 
      },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 34,
      version: 1,
      name: "Stage 34",
      stageType: "memory",
      rounds: 1,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { 
        misleadColors: true, 
        misleadChance: 0.6,
        textColor: true,
        textColorChance: 1.0,
        textPromptChance: 0.5 
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 35,
      version: 1,
      name: "Stage 35",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { 
        misleadColors: true, 
        misleadChance: 1.0, 
        backgroundColor: true,
        backgroundColorChance: 0.5,
        backgroundPromptChance: 0.5,
        textColor: true,
        textColorChance: 1.0,
        textPromptChance: 0.5 
      },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 36,
      version: 1,
      name: "Stage 36",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { 
        misleadColors: true, 
        misleadChance: 1.0, 
        backgroundColor: true,
        backgroundColorChance: 0.5,
        backgroundPromptChance: 0.5,
        textColor: true,
        textColorChance: 1.0,
        textPromptChance: 0.5 
      },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 37,
      version: 1,
      name: "Stage 37",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes", "diagonal"],
      modifiers: { mathOps: true, mathChance: 0.8 },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 38,
      version: 1,
      name: "Stage 38",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["letters"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, textColor: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 39,
      version: 1,
      name: "Stage 39",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters"],
      modifiers: { textColor: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 40,
      version: 1,
      name: "Stage 40",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { mathOps: true, mathChance: 0.6, textColor: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 41,
      version: 1,
      name: "Stage 41",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors", "directions", "diagonal"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, misleadColors: true, misleadChance: 0.6 },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 42,
      version: 1,
      name: "Stage 42",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes", "diagonal"],
      modifiers: { textColor: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 43,
      version: 1,
      name: "Stage 43",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["diagonal", "directions"],
      modifiers: {},
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 44,
      version: 1,
      name: "Stage 44",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { mathOps: true, mathChance: 1.0 },
      starTimes: { platinum: 2.5, gold: 3.5, silver: 12, bronze: 20 }
    },
    {
      id: 45,
      version: 1,
      name: "Stage 45",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions"],
      modifiers: { rotate: true },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
            {
      id: 46,
      version: 1,
      name: "Stage 46",
      stageType: "memory",
      rounds: 1,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions"],
      modifiers: { rotate: true },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 47,
      version: 1,
      name: "Stage 47",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors", "letters", "directions"],
      modifiers: { rotate: true },
      starTimes: { platinum: 8, gold: 9, silver: 12, bronze: 20 }
    },
    {
      id: 48,
      version: 1,
      name: "Stage 48",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "directions"],
      modifiers: { mathOps: true, mathChance: 0.6, rotate: true },
      starTimes: { platinum: 8, gold: 9, silver: 12, bronze: 20 }
    },
    {
      id: 49,
      version: 1,
      name: "Stage 49",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, rotate: true },
      starTimes: { platinum: 8, gold: 9, silver: 12, bronze: 20 }
    },
    {
      id: 50,
      version: 1,
      name: "Stage 50",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { mathOps: true, mathChance: 0.6, backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.75 },
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 51,
      version: 1,
      name: "Stage 51",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      cardCounts: { directions: 1 },
      modifiers: { rotate: true },
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 52,
      version: 1,
      name: "Stage 52",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      cardCounts: { directions: 1 },
      modifiers: { rotate: true },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 53,
      version: 1,
      name: "Stage 53",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["numbers", "colors"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, misleadColors: true, misleadChance: 0.6 },
      starTimes: { platinum: 2.5, gold: 3.5, silver: 12, bronze: 20 }
    },
    {
      id: 54,
      version: 1,
      name: "Stage 54",
      stageType: "memory",
      rounds: 1,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions", "diagonal"],
      modifiers: { rotate: true },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 55,
      version: 1,
      name: "Stage 55",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["directions", "diagonal"],
      modifiers: { rotate: true },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 56,
      version: 1,
      name: "Stage 56",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.2,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { backgroundColor: true, backgroundColorChance: 1.0, backgroundPromptChance: 0.5, misleadColors: true, misleadChance: 0.6, textColor: true, textColorChance: 1.0 },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 57,
      version: 1,
      name: "Stage 57",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["diagonal"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, rotate: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 58,
      version: 1,
      name: "Stage 58",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      modifiers: { misleadColors: true, misleadChance: 0.6, backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5 },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 59,
      version: 1,
      name: "Stage 59",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "diagonal"],
      modifiers: { mathOps: true, mathChance: 0.6, backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5 },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 60,
      version: 1,
      name: "Stage 60",
      stageType: "memory",
      rounds: 2,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["letters", "directions", "shapes"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5 },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 61,
      version: 1,
      name: "Stage 61",
      stageType: "memory",
      rounds: 2,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { 
        mathOps: true, 
        mathChance: 1.0,
        mathMinCount: 3,
        mathMaxCount: 3 
      },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 62,
      version: 1,
      name: "Stage 62",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { 
        mathOps: true, 
        mathChance: 1.0,
        mathMinCount: 4,
        mathMaxCount: 4 
      },
      starTimes: { platinum: 4, gold: 8, silver: 12, bronze: 20 }
    },
    {
      id: 63,
      version: 1,
      name: "Stage 63",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { mathOps: true, mathChance: 0.6, backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, mathMinCount: 1, mathMaxCount: 2 },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 64,
      version: 1,
      name: "Stage 64",
      stageType: "tutorial",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { glitch: true },
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 65,
      version: 1,
      name: "Stage 65",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters"],
      modifiers: { glitch: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 66,
      version: 1,
      name: "Stage 66",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors", "directions", "shapes"],
      modifiers: { glitch: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 67,
      version: 1,
      name: "Stage 67",
      stageType: "memory",
      rounds: 1,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      fixedCards: [
        { category: "numbers", label: "6" },
        { category: "numbers", label: "7" }
      ],
      modifiers: {},
      starTimes: { platinum: 1, gold: 2, silver: 12, bronze: 20 }
    },
    {
      id: 68,
      version: 1,
      name: "Stage 68",
      stageType: "memory",
      rounds: 2,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, misleadColors: true, misleadChance: 0.6, textColor: true, glitch: true, textColorChance: 1.0 },
      starTimes: { platinum: 8, gold: 10, silver: 12, bronze: 20 }
    },
    {
      id: 69,
      version: 1,
      name: "Stage 69",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { mathOps: true, mathChance: 0.6, glitch: true, mathMinCount: 1, mathMaxCount: 2, backgroundColor: true, backgroundColorChance: 1, backgroundPromptChance: 0.5 },
      starTimes: { platinum: 7, gold: 8, silver: 12, bronze: 20 }
    },
    {
      id: 70,
      version: 1,
      name: "Stage 70",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions", "diagonal"],
      modifiers: { rotate: true, glitch: true },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 71,
      version: 1,
      name: "Stage 71",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, misleadColors: true, misleadChance: 0.6, glitch: true },
      starTimes: { platinum: 8, gold: 10, silver: 12, bronze: 20 }
    },
    {
      id: 72,
      version: 1,
      name: "Stage 72",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.2,
      recallSeconds: 15,
      categories: ["letters"],
      modifiers: { textColor: true, textColorChance: 1.0 },
      starTimes: { platinum: 2.5, gold: 3.5, silver: 12, bronze: 20 }
    },
    {
      id: 73,
      version: 1,
      name: "Stage 73",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "shapes"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, glitch: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 74,
      version: 1,
      name: "Stage 74",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors", "letters", "directions"],
      cardCounts: { directions: 1 },
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, glitch: true, rotate: true },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 75,
      version: 1,
      name: "Stage 75",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.2,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: { mathOps: true, mathChance: 0.6, backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, textColor: true, textColorChance: 1.0 },
      starTimes: { platinum: 2.5, gold: 3.5, silver: 12, bronze: 20 }
    },
    {
      id: 76,
      version: 1,
      name: "Stage 76",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["diagonal"],
      modifiers: { rotate: true},
      starTimes: { platinum: 4.5, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 77,
      version: 1,
      name: "Stage 77",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 1.0,
        backgroundPromptChance: 0.5,
        misleadColors: true,
        misleadChance: 0.6,
        textColor: true,
        textColorChance: 1.0
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 78,
      version: 1,
      name: "Stage 78",
      stageType: "memory",
      rounds: 2,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters"],
      modifiers: { textColor: true, glitch: true, textColorChance: 1.0, textPromptChance: 0.5 },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 79,
      version: 1,
      name: "Stage 79",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 0.6,
        backgroundPromptChance: 0.5,
        misleadColors: true,
        misleadChance: 0.6,
        textColor: true,
        glitch: true
      },
      starTimes: { platinum: 8, gold: 9, silver: 12, bronze: 20 }
    },
    {
      id: 80,
      version: 1,
      name: "Stage 80",
      stageType: "memory",
      rounds: 2,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions", "diagonal"],
      modifiers: { rotate: true, glitch: true },
      starTimes: { platinum: 7, gold: 8, silver: 12, bronze: 20 }
    },
    {
      id: 81,
      version: 1,
      name: "Stage 81",
      stageType: "tutorial",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        mathOpsPlus: true,
        mathChance: 1.0,
        mathMinCount: 1,
        mathMaxCount: 1
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 82,
      version: 1,
      name: "Stage 82",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 1,
        backgroundPromptChance: 0.5,
        glitch: true,
        mathOpsPlus: true,
        mathChance: 0.6,
        mathMinCount: 1,
        mathMaxCount: 1
      },
      starTimes: { platinum: 7.5, gold: 8.5, silver: 12, bronze: 20 }
    },
    {
      id: 83,
      version: 1,
      name: "Stage 83",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.1,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        mathOpsPlus: true,
        mathChance: 1.0,
        mathMinCount: 1,
        mathMaxCount: 1
      },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 84,
      version: 1,
      name: "Stage 84",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { 
        mathOpsPlus: true, 
        mathChance: 0.6,
        mathMinCount: 2,
        mathMaxCount: 2
       },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 85,
      version: 1,
      name: "Stage 85",
      stageType: "memory",
      rounds: 3,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { 
        textColor: true, 
        mathOpsPlus: true, 
        mathChance: 0.6, 
        mathMinCount: 1,
        mathMaxCount: 1,
        textColorChance: 1.0
      },
      starTimes: { platinum: 8, gold: 9, silver: 12, bronze: 20 }
    },
    {
      id: 86,
      version: 1,
      name: "Stage 86",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      modifiers: {},
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 87,
      version: 1,
      name: "Stage 87",
      stageType: "memory",
      rounds: 1,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters", "directions", "shapes"],
      modifiers: { textColor: true },
      starTimes: { platinum: 3, gold: 4, silver: 12, bronze: 20 }
    },
    {
      id: 88,
      version: 1,
      name: "Stage 88",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.15,
      recallSeconds: 15,
      categories: ["directions"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5, rotate: true },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 89,
      version: 1,
      name: "Stage 89",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "directions"],
      modifiers: { rotate: true, mathOpsPlus: true, mathChance: 0.6 },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 90,
      version: 1,
      name: "Stage 90",
      stageType: "tutorial",
      rounds: 1,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: { fog: true },
      instructions: window.stageInstructions[90] || [],
      starTimes: { platinum: 2, gold: 3, silver: 12, bronze: 20 }
    },
    {
      id: 91,
      version: 1,
      name: "Stage 91",
      stageType: "memory",
      rounds: 3,
      cards: 1,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      modifiers: { fog: true },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 92,
      version: 1,
      name: "Stage 92",
      stageType: "memory",
      rounds: 1,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["colors"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 0.6,
        backgroundPromptChance: 0.5,
        misleadColors: true,
        misleadChance: 0.6,
        fog: true
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 93,
      version: 1,
      name: "Stage 93",
      stageType: "memory",
      rounds: 1,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["directions", "diagonal"],
      modifiers: { rotate: true, fog: true },
      starTimes: { platinum: 6, gold: 7, silver: 12, bronze: 20 }
    },
    {
      id: 94,
      version: 1,
      name: "Stage 94",
      stageType: "memory",
      rounds: 2,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        mathOps: true,
        mathChance: 0.6,
        backgroundColor: true,
        backgroundColorChance: 0.6,
        backgroundPromptChance: 0.5,
        fog: true,
        mathMinCount: 1,
        mathMaxCount: 1
      },
      starTimes: { platinum: 5, gold: 6, silver: 12, bronze: 20 }
    },
    {
      id: 95,
      version: 1,
      name: "Stage 95",
      stageType: "memory",
      rounds: 2,
      cards: 2,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        mathOps: true,
        mathOpsPlus: true,
        mathChance: 0.6,
        backgroundColor: true,
        backgroundColorChance: 0.6,
        backgroundPromptChance: 0.5,
        fog: true,
        mathMinCount: 1,
        mathMaxCount: 1
      },
      starTimes: { platinum: 7, gold: 8, silver: 12, bronze: 20 }
    },
    {
      id: 96,
      version: 1,
      name: "Stage 96",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "colors", "letters", "directions", "shapes"],
      modifiers: { glitch: true, fog: true },
      starTimes: { platinum: 14, gold: 15, silver: 12, bronze: 20 }
    },
    {
      id: 97,
      version: 1,
      name: "Stage 97",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.15,
      recallSeconds: 15,
      categories: ["letters"],
      modifiers: { backgroundColor: true, backgroundColorChance: 1, backgroundPromptChance: 0.5, textColor: true, textColorChance: 1.0 },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 98,
      version: 1,
      name: "Stage 98",
      stageType: "flash",
      rounds: 3,
      cards: 1,
      revealSeconds: 0.2,
      recallSeconds: 15,
      categories: ["numbers"],
      modifiers: {
        backgroundColor: true,
        backgroundColorChance: 0.6,
        backgroundPromptChance: 0.5,
        mathOpsPlus: true,
        mathChance: 0.6
      },
      starTimes: { platinum: 4, gold: 5, silver: 12, bronze: 20 }
    },
    {
      id: 99,
      version: 1,
      name: "Stage 99",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["shapes", "diagonal", "letters", "colors"],
      modifiers: { backgroundColor: true, backgroundColorChance: 0.6, backgroundPromptChance: 0.5 },
      starTimes: { platinum: 9, gold: 10, silver: 12, bronze: 20 }
    },
    {
      id: 100,
      version: 1,
      name: "Stage 100",
      stageType: "memory",
      rounds: 3,
      cards: 4,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "letters", "shapes", "colors"],
      modifiers: { fog: true },
      starTimes: { platinum: 11, gold: 12, silver: 12, bronze: 20 }
    },
    {
      id: 101,
      version: 1,
      name: "Stage 101",
      stageType: "memory",
      rounds: 3,
      cards: 3,
      revealSeconds: 15,
      recallSeconds: 15,
      categories: ["numbers", "directions", "letters", "shapes"],
      modifiers: { rotate: true, glitch: true, fog: true },
      starTimes: { platinum: 9, gold: 10, silver: 12, bronze: 20 }
    }
  ];
})();

  // mathOps: true,
  // mathChance: 0.9,
  // misleadColors: true,
  // misleadChance: 0.4,
  // backgroundColor: true,
  // backgroundColorChance: 1.0,
  // backgroundPromptChance: 0.5
  // swapCards: true,
  // swapChance: 0.3,
  // platformer: false,
  // glitch: false,
  // fog: false,
  // ads: false
